/**
 * EduGuard — Design Tokens e Constantes de Tema
 * Centraliza cores, espaçamentos e configurações visuais reutilizáveis.
 */

export const THEME = {
  colors: {
    primary: 'var(--primary)',
    primaryHover: 'var(--primary-hover)',
    primarySubtle: 'var(--primary-subtle)',
    secondary: 'var(--secondary)',
    success: 'var(--success)',
    successBg: 'var(--success-bg)',
    danger: 'var(--danger)',
    dangerBg: 'var(--danger-bg)',
    warning: 'var(--warning)',
    warningBg: 'var(--warning-bg)',
    info: 'var(--info)',
    infoBg: 'var(--info-bg)',
    textPrimary: 'var(--text-primary)',
    textSecondary: 'var(--text-secondary)',
    textMuted: 'var(--text-muted)',
    surface: 'var(--surface)',
    surfaceLight: 'var(--surface-light)',
    border: 'var(--border)',
  },
};

/** Estilos reutilizáveis para componentes de página */
export const PAGE_STYLES = {
  pageTitle: {
    fontSize: '1.5rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-heading)',
  },
  pageSubtitle: {
    color: 'var(--text-secondary)',
    fontSize: '0.85rem',
    marginTop: '0.25rem',
  },
  searchBar: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: 'var(--surface)',
    border: '1.5px solid var(--border)',
    borderRadius: 'var(--radius-md)',
    padding: '0.5rem 0.875rem',
    width: '100%',
    maxWidth: '400px',
  },
  searchInput: {
    background: 'transparent',
    border: 'none',
    outline: 'none',
    fontSize: '0.85rem',
    width: '100%',
    color: 'var(--text-primary)',
  },
  errorBox: {
    marginBottom: '1rem',
    padding: '0.75rem',
    backgroundColor: 'var(--danger-bg)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    borderRadius: 'var(--radius-md)',
    color: 'var(--danger)',
    fontSize: '0.85rem',
  },
  successBox: {
    marginBottom: '1rem',
    padding: '0.75rem',
    backgroundColor: 'var(--success-bg)',
    border: '1px solid rgba(16, 185, 129, 0.2)',
    borderRadius: 'var(--radius-md)',
    color: 'var(--success)',
    fontSize: '0.85rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  iconBox: (color) => ({
    width: '44px',
    height: '44px',
    borderRadius: 'var(--radius-lg)',
    background: `${color}14`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  }),
  cardSection: {
    backgroundColor: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-lg)',
    padding: '1.5rem',
    boxShadow: 'var(--shadow-card)',
  },
  modalActions: {
    marginTop: '1.5rem',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '0.75rem',
  },
  detailHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem',
    backgroundColor: 'var(--surface-light)',
    borderRadius: 'var(--radius-lg)',
    marginBottom: '1.5rem',
  },
  avatar: (size = 40) => ({
    width: `${size}px`,
    height: `${size}px`,
    borderRadius: 'var(--radius-full)',
    background: 'linear-gradient(135deg, var(--primary), var(--secondary))',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: 700,
    fontSize: `${size * 0.3}px`,
    flexShrink: 0,
  }),
  listItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.75rem 1rem',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-md)',
    backgroundColor: 'var(--surface)',
  },
};

/** Configuração de rotas */
export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  ALUNOS: '/alunos',
  RESPONSAVEIS: '/responsaveis',
  EQUIPE: '/equipe',
  TURMAS: '/turmas',
  PONTO: '/ponto',
  ROTINA: '/rotina',
  MEDICACAO: '/medicacao',
  AVISOS: '/avisos',
  HISTORICO: '/historico',
  LOGS: '/logs',
  PERFIL: '/perfil',
};
